Update index.js
js-tasks-ru/js-20220909_cat-malum pull request #1
Opened 2022-09-10 09:21 UTC by Cat-Malum

2022-09-10 09:21 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @dosandk должен запустить тесты.

2022-09-11 15:35 UTC, dosandk commented on 01-intro/1-sum/index.js
> +	return m + n;
good 👍

2022-09-11 15:36 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	let newArr = arr.map(item => item);
* `newArr` - это `const`
* `map` - это не самый удачный способ скопировать массив

2022-09-11 15:36 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +			return a.localeCompare(b, 0, {caseFirst: 'upper'});
второй аргумент должен быть списком локалей!

2022-09-11 15:37 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +	for (let i = 0; i < arr.length; i++) {
пожалуйста используйте `for...of` для итерации по массивам!

2022-09-11 15:37 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +		if (arr.includes(undefined)) arr.splice(i, 1);
`splice` на практике мы не используем - он мутирует массив

2022-09-11 15:37 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +		if (arr.includes(undefined)) arr.splice(i, 1);
от этой проверки `arr.includes(undefined)` следует избавится!

2022-09-11 15:38 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +		if (fields.includes(item[0])) return item;
функция коллбек метода `filter` должна возвращать `true` либо `false` но никак не `item`

2022-09-11 15:40 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +	let arr = Object.entries(obj).filter(item => {
попробуйте избавиться от `filter`, обратите внимание на замечания выше

2022-09-11 15:40 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-09-15 22:20 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +	const newArr = arr.slice();
`const newArr = [...arr]`

2022-09-15 22:22 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +			return b.localeCompare(a, ['ru', 'en-US'], {caseFirst: 'lower'});
это было бы неплохо вынести в ф-цию:
```
const compare = (first, second, caseFirst) => {
  return first.localeCompare(second, ['ru', 'en-US'], {caseFirst})
};

newArr.sort((a, b) => {
  if (param === 'asc') {
			return compare(a, b, 'upper')
	}

  if (param === 'desc') {
    return compare(b, a, 'lower')
  }
});
```

2022-09-15 22:22 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +	Object.entries(obj).forEach(([key, value]) => {
good 👍

2022-09-15 22:23 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
>  export const omit = (obj, ...fields) => {
good 👍

2022-09-15 22:23 UTC, dosandk approved these changes
good 👍

2022-09-15 22:24 UTC, merged